### ISSUE TITLE
self.interpreter is not callable

### ISSUE THREAD

**Issue by airVoidy** [PrAsAnNaRePo/LocalAgent#1]
You are a personal assistant who has wide knowledge in world topics.
Check out my IP address with python
agent initialized with stream, If you want to start agent with non streaming pass the regular api uri instead.
Code interpreter is enabled, creating code_interpreter tool.
 User wants me to find their IP address using python. I should use code_interpreter to run the code and return the output.
Action: code_interpreter
Action Input: {"task": "Write a Python script to get the IP address and save it in a text file."}
💭 User wants me to find their IP address using python. I should use code_interpreter to run the code and return the output.
Traceback (most recent call last):
  File "/mnt/e/LLM/llm_pf.py", line 22, in <module>
    agent.go_flow(args.flow)
  File "/home/voidy/miniconda3/lib/python3.11/site-packages/localagent/initialize_agents.py", line 241, in go_flow
    func_out = f"This is code_interpreter tool (not user). Here is the result for your task:\n{self.interpreter(**func_args)}\nTake this to user."

TypeError: 'Interpreter' object is not callable

**Comment by PrAsAnNaRePo** [comment]
Thanks for your feedback!
Update your package using `pip install -U localagent`
This should be work. Let me know if you are facing any other issues.
